version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.27.0
    - 8.28.0
    - 8.29.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.0
    - 8.32.1
    - 8.33.0
    - 8.33.1
    - 8.34.0
    - 8.35.0
    - 8.35.1
    - 8.36.1
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.4.0
  - dependency-name: fakerphp/faker
    versions:
    - 1.14.0
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.3
    - 2.18.4
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
