version: '3.7'

services:
  test:
    container_name: test
    depends_on:
      - db
    build:
      target: test
      context: .
    ports:
      - "8002:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: develop
      DB_USERNAME: root
      DB_PASSWORD: 123456
  db:
    image: devesharp/mariadb:10.6.1
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MARIADB_MULTIPLE_DATABASE: develop,testing
