version: '3.7'

services:
  app:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .env:/app/.env
  db:
    image: postgres:13.0
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: develop
