version: '3.7'

services:
  test:
    container_name: test
    depends_on:
      - db
    build:
      target: test
      context: .
    ports:
      - "8002:80"
    volumes:
      - .env:/app/.env
  db:
    image: postgres:13.0
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: develop
